version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directories:
      - "/"
      - "docs"
    schedule:
      interval: "daily"
    reviewers:
      - "Mark-j-Lawrence"
